2025-01-08 18:36:09,002 - asyncio - DEBUG - Using proactor: IocpProactor
2025-01-08 18:36:09,003 - root - INFO - Bot PID: 22504
2025-01-08 18:36:09,004 - root - INFO - Initializing bot application...
2025-01-08 18:36:09,039 - root - INFO - Starting bot application...
2025-01-08 18:36:09,039 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getMe` with parameters `{}`
2025-01-08 18:36:09,047 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2025-01-08 18:36:09,257 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x0000020FA7B800D0>
2025-01-08 18:36:09,258 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x0000020F96D55AC0> server_hostname='api.telegram.org' timeout=5.0
2025-01-08 18:36:09,465 - httpcore.connection - DEBUG - start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x0000020FA7B42F50>
2025-01-08 18:36:09,466 - httpcore.http11 - DEBUG - send_request_headers.started request=<Request [b'POST']>
2025-01-08 18:36:09,466 - httpcore.http11 - DEBUG - send_request_headers.complete
2025-01-08 18:36:09,466 - httpcore.http11 - DEBUG - send_request_body.started request=<Request [b'POST']>
2025-01-08 18:36:09,466 - httpcore.http11 - DEBUG - send_request_body.complete
2025-01-08 18:36:09,467 - httpcore.http11 - DEBUG - receive_response_headers.started request=<Request [b'POST']>
2025-01-08 18:36:09,680 - httpcore.http11 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Server', b'nginx/1.18.0'), (b'Date', b'Wed, 08 Jan 2025 22:36:09 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'267'), (b'Connection', b'keep-alive'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains; preload'), (b'Access-Control-Allow-Origin', b'*'), (b'Access-Control-Allow-Methods', b'GET, POST, OPTIONS'), (b'Access-Control-Expose-Headers', b'Content-Length,Content-Type,Date,Server,Connection')])
2025-01-08 18:36:09,680 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7371766055:AAFyDF7EpR3dStXajJXR7c_1Rf1EuNbprEk/getMe "HTTP/1.1 200 OK"
2025-01-08 18:36:09,681 - httpcore.http11 - DEBUG - receive_response_body.started request=<Request [b'POST']>
2025-01-08 18:36:09,681 - httpcore.http11 - DEBUG - receive_response_body.complete
2025-01-08 18:36:09,681 - httpcore.http11 - DEBUG - response_closed.started
2025-01-08 18:36:09,682 - httpcore.http11 - DEBUG - response_closed.complete
2025-01-08 18:36:36,161 - asyncio - DEBUG - Using proactor: IocpProactor
2025-01-08 18:36:36,163 - root - INFO - Bot PID: 7140
2025-01-08 18:36:36,163 - root - INFO - Initializing bot application...
2025-01-08 18:36:36,191 - root - INFO - Starting bot application...
2025-01-08 18:36:36,192 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getMe` with parameters `{}`
2025-01-08 18:36:36,198 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2025-01-08 18:36:36,402 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x00000233A78A3D00>
2025-01-08 18:36:36,403 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x0000023396AB5AC0> server_hostname='api.telegram.org' timeout=5.0
2025-01-08 18:36:36,606 - httpcore.connection - DEBUG - start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x00000233A78A2BC0>
2025-01-08 18:36:36,606 - httpcore.http11 - DEBUG - send_request_headers.started request=<Request [b'POST']>
2025-01-08 18:36:36,606 - httpcore.http11 - DEBUG - send_request_headers.complete
2025-01-08 18:36:36,607 - httpcore.http11 - DEBUG - send_request_body.started request=<Request [b'POST']>
2025-01-08 18:36:36,607 - httpcore.http11 - DEBUG - send_request_body.complete
2025-01-08 18:36:36,607 - httpcore.http11 - DEBUG - receive_response_headers.started request=<Request [b'POST']>
2025-01-08 18:36:36,808 - httpcore.http11 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Server', b'nginx/1.18.0'), (b'Date', b'Wed, 08 Jan 2025 22:36:36 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'267'), (b'Connection', b'keep-alive'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains; preload'), (b'Access-Control-Allow-Origin', b'*'), (b'Access-Control-Allow-Methods', b'GET, POST, OPTIONS'), (b'Access-Control-Expose-Headers', b'Content-Length,Content-Type,Date,Server,Connection')])
2025-01-08 18:36:36,809 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7371766055:AAFyDF7EpR3dStXajJXR7c_1Rf1EuNbprEk/getMe "HTTP/1.1 200 OK"
2025-01-08 18:36:36,809 - httpcore.http11 - DEBUG - receive_response_body.started request=<Request [b'POST']>
2025-01-08 18:36:36,810 - httpcore.http11 - DEBUG - receive_response_body.complete
2025-01-08 18:36:36,810 - httpcore.http11 - DEBUG - response_closed.started
2025-01-08 18:36:36,811 - httpcore.http11 - DEBUG - response_closed.complete
2025-01-08 18:36:43,040 - asyncio - DEBUG - Using proactor: IocpProactor
2025-01-08 18:36:43,042 - root - INFO - Bot PID: 19032
2025-01-08 18:36:43,042 - root - INFO - Initializing bot application...
2025-01-08 18:36:43,072 - root - INFO - Starting bot application...
2025-01-08 18:36:43,072 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getMe` with parameters `{}`
2025-01-08 18:36:43,081 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2025-01-08 18:36:43,289 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x000001761F36FCD0>
2025-01-08 18:36:43,289 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x000001760E585AC0> server_hostname='api.telegram.org' timeout=5.0
2025-01-08 18:36:43,493 - httpcore.connection - DEBUG - start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x000001761F36EB90>
2025-01-08 18:36:43,494 - httpcore.http11 - DEBUG - send_request_headers.started request=<Request [b'POST']>
2025-01-08 18:36:43,494 - httpcore.http11 - DEBUG - send_request_headers.complete
2025-01-08 18:36:43,494 - httpcore.http11 - DEBUG - send_request_body.started request=<Request [b'POST']>
2025-01-08 18:36:43,494 - httpcore.http11 - DEBUG - send_request_body.complete
2025-01-08 18:36:43,494 - httpcore.http11 - DEBUG - receive_response_headers.started request=<Request [b'POST']>
2025-01-08 18:36:43,698 - httpcore.http11 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Server', b'nginx/1.18.0'), (b'Date', b'Wed, 08 Jan 2025 22:36:43 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'267'), (b'Connection', b'keep-alive'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains; preload'), (b'Access-Control-Allow-Origin', b'*'), (b'Access-Control-Allow-Methods', b'GET, POST, OPTIONS'), (b'Access-Control-Expose-Headers', b'Content-Length,Content-Type,Date,Server,Connection')])
2025-01-08 18:36:43,700 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7371766055:AAFyDF7EpR3dStXajJXR7c_1Rf1EuNbprEk/getMe "HTTP/1.1 200 OK"
2025-01-08 18:36:43,700 - httpcore.http11 - DEBUG - receive_response_body.started request=<Request [b'POST']>
2025-01-08 18:36:43,701 - httpcore.http11 - DEBUG - receive_response_body.complete
2025-01-08 18:36:43,701 - httpcore.http11 - DEBUG - response_closed.started
2025-01-08 18:36:43,701 - httpcore.http11 - DEBUG - response_closed.complete
2025-01-08 18:36:53,339 - asyncio - DEBUG - Using proactor: IocpProactor
2025-01-08 18:36:53,341 - root - INFO - Bot PID: 7588
2025-01-08 18:36:53,341 - root - INFO - Initializing bot application...
2025-01-08 18:36:53,375 - root - INFO - Starting bot application...
2025-01-08 18:36:53,375 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getMe` with parameters `{}`
2025-01-08 18:36:53,383 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2025-01-08 18:36:53,583 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x000001C02D35C070>
2025-01-08 18:36:53,584 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x000001C01C535AC0> server_hostname='api.telegram.org' timeout=5.0
2025-01-08 18:36:53,782 - httpcore.connection - DEBUG - start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x000001C02D31EEF0>
2025-01-08 18:36:53,782 - httpcore.http11 - DEBUG - send_request_headers.started request=<Request [b'POST']>
2025-01-08 18:36:53,783 - httpcore.http11 - DEBUG - send_request_headers.complete
2025-01-08 18:36:53,783 - httpcore.http11 - DEBUG - send_request_body.started request=<Request [b'POST']>
2025-01-08 18:36:53,783 - httpcore.http11 - DEBUG - send_request_body.complete
2025-01-08 18:36:53,783 - httpcore.http11 - DEBUG - receive_response_headers.started request=<Request [b'POST']>
2025-01-08 18:36:53,980 - httpcore.http11 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Server', b'nginx/1.18.0'), (b'Date', b'Wed, 08 Jan 2025 22:36:53 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'267'), (b'Connection', b'keep-alive'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains; preload'), (b'Access-Control-Allow-Origin', b'*'), (b'Access-Control-Allow-Methods', b'GET, POST, OPTIONS'), (b'Access-Control-Expose-Headers', b'Content-Length,Content-Type,Date,Server,Connection')])
2025-01-08 18:36:53,981 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7371766055:AAFyDF7EpR3dStXajJXR7c_1Rf1EuNbprEk/getMe "HTTP/1.1 200 OK"
2025-01-08 18:36:53,981 - httpcore.http11 - DEBUG - receive_response_body.started request=<Request [b'POST']>
2025-01-08 18:36:53,982 - httpcore.http11 - DEBUG - receive_response_body.complete
2025-01-08 18:36:53,982 - httpcore.http11 - DEBUG - response_closed.started
2025-01-08 18:36:53,982 - httpcore.http11 - DEBUG - response_closed.complete
2025-01-08 18:37:19,565 - asyncio - DEBUG - Using proactor: IocpProactor
2025-01-08 18:37:19,567 - root - INFO - Bot PID: 28276
2025-01-08 18:37:19,568 - root - INFO - Initializing bot application...
2025-01-08 18:37:19,599 - root - INFO - Starting bot application...
2025-01-08 18:37:19,600 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getMe` with parameters `{}`
2025-01-08 18:37:19,609 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2025-01-08 18:37:19,810 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x000001C7621B3EE0>
2025-01-08 18:37:19,811 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x000001C7513CD9C0> server_hostname='api.telegram.org' timeout=5.0
2025-01-08 18:37:20,012 - httpcore.connection - DEBUG - start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x000001C7621B2DA0>
2025-01-08 18:37:20,013 - httpcore.http11 - DEBUG - send_request_headers.started request=<Request [b'POST']>
2025-01-08 18:37:20,014 - httpcore.http11 - DEBUG - send_request_headers.complete
2025-01-08 18:37:20,014 - httpcore.http11 - DEBUG - send_request_body.started request=<Request [b'POST']>
2025-01-08 18:37:20,015 - httpcore.http11 - DEBUG - send_request_body.complete
2025-01-08 18:37:20,015 - httpcore.http11 - DEBUG - receive_response_headers.started request=<Request [b'POST']>
2025-01-08 18:37:20,221 - httpcore.http11 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Server', b'nginx/1.18.0'), (b'Date', b'Wed, 08 Jan 2025 22:37:19 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'267'), (b'Connection', b'keep-alive'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains; preload'), (b'Access-Control-Allow-Origin', b'*'), (b'Access-Control-Allow-Methods', b'GET, POST, OPTIONS'), (b'Access-Control-Expose-Headers', b'Content-Length,Content-Type,Date,Server,Connection')])
2025-01-08 18:37:20,222 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7371766055:AAFyDF7EpR3dStXajJXR7c_1Rf1EuNbprEk/getMe "HTTP/1.1 200 OK"
2025-01-08 18:37:20,223 - httpcore.http11 - DEBUG - receive_response_body.started request=<Request [b'POST']>
2025-01-08 18:37:20,224 - httpcore.http11 - DEBUG - receive_response_body.complete
2025-01-08 18:37:20,224 - httpcore.http11 - DEBUG - response_closed.started
2025-01-08 18:37:20,225 - httpcore.http11 - DEBUG - response_closed.complete
2025-01-08 18:37:20,245 - telegram.ext.ExtBot - DEBUG - This Bot is already initialized.
2025-01-08 18:37:20,245 - telegram.ext.Application - INFO - Application started
2025-01-08 18:37:20,246 - root - INFO - Saved bot state: running
2025-01-08 18:37:20,247 - root - INFO - Bot started successfully
2025-01-08 18:37:20,247 - root - INFO - Starting polling...
2025-01-08 18:37:20,248 - root - ERROR - Error in polling: This event loop is already running
2025-01-08 18:37:20,249 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\ext\_application.py", line 1069, in __run
    loop.run_until_complete(self.initialize())
  File "C:\Users\eliec\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 617, in run_until_complete
    self._check_running()
  File "C:\Users\eliec\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 577, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\main.py", line 328, in _run_polling
    await self.application.run_polling(stop_signals=(), close_loop=False)
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\ext\_application.py", line 868, in run_polling
    return self.__run(
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\ext\_application.py", line 1090, in __run
    loop.run_until_complete(self.stop())
  File "C:\Users\eliec\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 617, in run_until_complete
    self._check_running()
  File "C:\Users\eliec\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 577, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

2025-01-08 18:37:20,257 - root - INFO - Shutting down bot...
2025-01-08 18:37:20,257 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2025-01-08 18:37:20,258 - telegram.ext.Application - DEBUG - Waiting for update_queue to join
2025-01-08 18:37:20,258 - telegram.ext.Application - DEBUG - Application stopped fetching of updates.
2025-01-08 18:37:20,259 - telegram.ext.Application - DEBUG - Waiting for `create_task` calls to be processed
2025-01-08 18:37:20,259 - telegram.ext.Application - INFO - Application.stop() complete
2025-01-08 18:37:20,260 - httpcore.connection - DEBUG - close.started
2025-01-08 18:37:20,261 - httpcore.connection - DEBUG - close.complete
2025-01-08 18:37:20,262 - telegram.ext.ExtBot - DEBUG - This Bot is already shut down. Returning.
2025-01-08 18:37:20,262 - telegram.ext.Updater - DEBUG - Shut down of Updater complete
2025-01-08 18:37:20,262 - root - INFO - Bot shutdown complete
2025-01-08 18:37:20,263 - root - INFO - Cleaned up C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\bot.pid
2025-01-08 18:37:20,264 - root - INFO - Cleaned up C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\bot_state.json
2025-01-08 18:38:07,317 - asyncio - DEBUG - Using proactor: IocpProactor
2025-01-08 18:38:07,319 - root - INFO - Bot PID: 22516
2025-01-08 18:38:07,319 - root - INFO - Initializing bot application...
2025-01-08 18:38:07,348 - root - INFO - Starting bot application...
2025-01-08 18:38:07,348 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getMe` with parameters `{}`
2025-01-08 18:38:07,354 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2025-01-08 18:38:07,790 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x000001E6370705B0>
2025-01-08 18:38:07,790 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x000001E626255AC0> server_hostname='api.telegram.org' timeout=5.0
2025-01-08 18:38:07,988 - httpcore.connection - DEBUG - start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x000001E637043430>
2025-01-08 18:38:07,989 - httpcore.http11 - DEBUG - send_request_headers.started request=<Request [b'POST']>
2025-01-08 18:38:07,990 - httpcore.http11 - DEBUG - send_request_headers.complete
2025-01-08 18:38:07,990 - httpcore.http11 - DEBUG - send_request_body.started request=<Request [b'POST']>
2025-01-08 18:38:07,990 - httpcore.http11 - DEBUG - send_request_body.complete
2025-01-08 18:38:07,991 - httpcore.http11 - DEBUG - receive_response_headers.started request=<Request [b'POST']>
2025-01-08 18:38:08,181 - httpcore.http11 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Server', b'nginx/1.18.0'), (b'Date', b'Wed, 08 Jan 2025 22:38:07 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'267'), (b'Connection', b'keep-alive'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains; preload'), (b'Access-Control-Allow-Origin', b'*'), (b'Access-Control-Allow-Methods', b'GET, POST, OPTIONS'), (b'Access-Control-Expose-Headers', b'Content-Length,Content-Type,Date,Server,Connection')])
2025-01-08 18:38:08,181 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7371766055:AAFyDF7EpR3dStXajJXR7c_1Rf1EuNbprEk/getMe "HTTP/1.1 200 OK"
2025-01-08 18:38:08,181 - httpcore.http11 - DEBUG - receive_response_body.started request=<Request [b'POST']>
2025-01-08 18:38:08,182 - httpcore.http11 - DEBUG - receive_response_body.complete
2025-01-08 18:38:08,182 - httpcore.http11 - DEBUG - response_closed.started
2025-01-08 18:38:08,182 - httpcore.http11 - DEBUG - response_closed.complete
2025-01-08 18:38:25,075 - asyncio - DEBUG - Using proactor: IocpProactor
2025-01-08 18:38:25,077 - root - INFO - Bot PID: 15904
2025-01-08 18:38:25,077 - root - INFO - Initializing bot application...
2025-01-08 18:38:25,108 - root - INFO - Starting bot application...
2025-01-08 18:38:25,109 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getMe` with parameters `{}`
2025-01-08 18:38:25,115 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2025-01-08 18:38:25,319 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x000001BF81010430>
2025-01-08 18:38:25,319 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x000001BFF01B5AC0> server_hostname='api.telegram.org' timeout=5.0
2025-01-08 18:38:25,521 - httpcore.connection - DEBUG - start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x000001BF80FE32B0>
2025-01-08 18:38:25,521 - httpcore.http11 - DEBUG - send_request_headers.started request=<Request [b'POST']>
2025-01-08 18:38:25,522 - httpcore.http11 - DEBUG - send_request_headers.complete
2025-01-08 18:38:25,522 - httpcore.http11 - DEBUG - send_request_body.started request=<Request [b'POST']>
2025-01-08 18:38:25,522 - httpcore.http11 - DEBUG - send_request_body.complete
2025-01-08 18:38:25,522 - httpcore.http11 - DEBUG - receive_response_headers.started request=<Request [b'POST']>
2025-01-08 18:38:25,719 - httpcore.http11 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Server', b'nginx/1.18.0'), (b'Date', b'Wed, 08 Jan 2025 22:38:25 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'267'), (b'Connection', b'keep-alive'), (b'Strict-Transport-Security', b'max-age=31536000; includeSubDomains; preload'), (b'Access-Control-Allow-Origin', b'*'), (b'Access-Control-Allow-Methods', b'GET, POST, OPTIONS'), (b'Access-Control-Expose-Headers', b'Content-Length,Content-Type,Date,Server,Connection')])
2025-01-08 18:38:25,720 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7371766055:AAFyDF7EpR3dStXajJXR7c_1Rf1EuNbprEk/getMe "HTTP/1.1 200 OK"
2025-01-08 18:38:25,720 - httpcore.http11 - DEBUG - receive_response_body.started request=<Request [b'POST']>
2025-01-08 18:38:25,720 - httpcore.http11 - DEBUG - receive_response_body.complete
2025-01-08 18:38:25,720 - httpcore.http11 - DEBUG - response_closed.started
2025-01-08 18:38:25,720 - httpcore.http11 - DEBUG - response_closed.complete
2025-01-08 18:39:15,182 - asyncio - DEBUG - Using proactor: IocpProactor
2025-01-08 18:39:15,184 - root - INFO - Bot PID: 16228
2025-01-08 18:39:15,185 - root - INFO - Initializing bot application...
2025-01-08 18:39:15,219 - root - INFO - Starting bot application...
2025-01-08 18:39:15,220 - telegram.ext.ExtBot - DEBUG - Calling Bot API endpoint `getMe` with parameters `{}`
2025-01-08 18:39:15,228 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2025-01-08 18:39:15,327 - httpcore.connection - DEBUG - connect_tcp.failed exception=CancelledError()
2025-01-08 18:39:15,328 - root - INFO - Shutting down bot...
2025-01-08 18:39:15,329 - root - ERROR - Error during shutdown: This Application is not running!
2025-01-08 18:39:15,342 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\main.py", line 303, in start
    await self.application.initialize()
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\ext\_application.py", line 487, in initialize
    await self.bot.initialize()
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\ext\_extbot.py", line 300, in initialize
    await super().initialize()
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\_bot.py", line 763, in initialize
    await self.get_me()
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\ext\_extbot.py", line 1957, in get_me
    return await super().get_me(
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\_bot.py", line 895, in get_me
    result = await self._post(
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\_bot.py", line 619, in _post
    return await self._do_post(
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\ext\_extbot.py", line 354, in _do_post
    return await super()._do_post(
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\_bot.py", line 648, in _do_post
    result = await request.post(
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\request\_baserequest.py", line 202, in post
    result = await self._request_wrapper(
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\request\_baserequest.py", line 334, in _request_wrapper
    code, payload = await self.do_request(
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\request\_httpxrequest.py", line 293, in do_request
    res = await self._client.request(
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\httpx\_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\httpx\_client.py", line 1629, in send
    response = await self._send_handling_auth(
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\httpx\_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\httpx\_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\httpx\_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\httpcore\_async\connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\httpcore\_backends\auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\httpcore\_backends\anyio.py", line 115, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\anyio\_core\_sockets.py", line 227, in connect_tcp
    async with create_task_group() as tg:
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\anyio\_core\_sockets.py", line 232, in connect_tcp
    await event.wait()
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 1766, in wait
    await self._event.wait()
  File "C:\Users\eliec\AppData\Local\Programs\Python\Python310\lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\main.py", line 359, in shutdown
    await self.application.stop()
  File "C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\.venv\lib\site-packages\telegram\ext\_application.py", line 661, in stop
    raise RuntimeError("This Application is not running!")
RuntimeError: This Application is not running!

2025-01-08 18:39:15,352 - root - INFO - Cleaned up C:\Users\eliec\Desktop\Developments\dexfren-ai-telegram-agent\bot.pid
2025-01-08 18:39:15,355 - root - INFO - Bot stopped by user
